name: game_template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  google_mobile_ads: ^4.0.0
  audioplayers: ^5.2.1
  video_player: ^2.8.2
  games_services: ^4.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.2
  provider: ^6.1.1
  gap: ^3.0.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.6
  flutter_lints: ^2.0.0

icons_launcher:
  image_path: "assets/marketing/app-icon-1024.png"
  platforms:
    web:
      enable: true
      image_path: "assets/marketing/app-icon-512.png"
      favicon_path: "assets/marketing/app-icon-512.png"
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
flutter_native_splash:
  image: "assets/marketing/app-icon-1024.png"
  color: “42a5f5”
  android_disable_fullscreen: true
  fullscreen: true

flutter_icons:
  ios: true
  android: true
  image_path: "assets/marketing/app-icon-1024.png"

flutter:
  uses-material-design: true

  assets:
     - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


